# DS109 Python : Lesson Nine Matrix Operations

In [2]:
import numpy as np

### Create a five element array using your favorite numbers named `myFavorites`.

In [3]:
myFavorites = np.array([1,2,3,4,5])

In [4]:
myFavorites

array([1, 2, 3, 4, 5])

### Perform each of the five aggregate functions on your array.

In [5]:
myFavorites.max()

5

In [6]:
myFavorites.min()

1

In [7]:
myFavorites.mean()

3.0

In [8]:
myFavorites.std()

1.4142135623730951

In [9]:
myFavorites.sum()

15

### Create a five element array containing only ones named `OneArrayToRuleThemAll`.

In [10]:
OneArrayToRuleThemAll = np.ones(5)

In [11]:
OneArrayToRuleThemAll

array([1., 1., 1., 1., 1.])

### Add `myFavorites` and `OneArrayToRuleThemAll`.

In [12]:
array = myFavorites + OneArrayToRuleThemAll
array

array([2., 3., 4., 5., 6.])

### Multiply every element in `myFavorites` by two.

In [13]:
array2 = myFavorites * 2
array2

array([ 2,  4,  6,  8, 10])

### Call the third element in `myFavorites` using indexing.

In [14]:
myFavorites[2]

3

### Create a four element, two-by-two matrix of numbers named `TheMatrixHasYou`.

In [18]:
TheMatrixHasYou = np.array([[6, 7],[8, 9]])
TheMatrixHasYou

array([[6, 7],
       [8, 9]])

### Access the upper left element in `TheMatrixHasYou` using indexing.

In [21]:
TheMatrixHasYou[0:1,0]

array([6])

### Find the largest number in each row for `TheMatrixHasYou`.

In [ ]:
TheMatrixHasYou.max(axis=1)

### Reshape `TheMatrixHasYou` into a matrix with one row and four columns.

In [22]:
TheMatrixHasYou.reshape(1,4)

array([[6, 7, 8, 9]])